// Cosmo Canyon — spec-compile (§15g phase 7 / §15b). DETERMINISTIC compile of the Ready SPEC set into the
// planner north-star + the authority hash. Authority = the set of Ready Spec assets.
//
// authorityHashOf(specs) is the SINGLE definition of the authority hash. spec-core.specAuthoritySha() (called
// EVERY sense, from the derived index — fast, no file reads) AND compileSpecs() (writes the doc; called on an
// authority-change event + in plan-prep) BOTH use it → the doc + the hash can NEVER disagree (15.24: no
// independent recompute — a caller latches on the EXACT hash compileSpecs returned).
//
// compileSpecs() holds the `assets-index` lock (rank 2) for the WHOLE scan+write (15.24 — snapshot-consistent
// set; a torn read is not observable while both hosts are strictly serial, so this lock is a forward-looking
// guard for the concurrency toggle; the §13.44 markers-last invariant is preserved via temp+rename). It writes
// `control/spec-doc.md` (planner north-star = concatenation of Ready spec BODIES; a Not-Ready spec is EXCLUDED
// = the primary WIP wall) + `control/spec-index.json` (machine list), and RETURNS {hash, ids, count}.
//
// ROOT-parameterized via env `CC_CONTROL` (scratch-testable). PURE fs + lock.mjs + the store's readIndex/readAsset.
import { acquire, release } from "./lock.mjs";
import { readIndex, readAsset } from "./assets.mjs";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, renameSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const CC = "C:/Vibes/cosmo-canyon";
function controlRoot() { return process.env.CC_CONTROL || `${CC}/control`; }
function locksDir() { return `${controlRoot()}/locks`; }
function assetsDir() { return `${controlRoot()}/assets`; }
function specDocPath() { return `${controlRoot()}/spec-doc.md`; }
function specIndexPath() { return `${controlRoot()}/spec-index.json`; }
function knownGoodPath() { return `${controlRoot()}/.authority-known-good`; }

const nowIso = () => new Date().toISOString();
function readJsonSafe(p, d = null) { try { return JSON.parse(readFileSync(p, "utf8")); } catch { return d; } }
function atomicWrite(p, s) { const t = `${p}.tmp`; writeFileSync(t, s); renameSync(t, p); }
function sha1hex(s) { return createHash("sha1").update(s).digest("hex"); }

// The Ready SPEC set, read from the derived index (fast — no per-asset file reads). state==="ready" && kind==="spec".
// A Not-Ready spec is NOT authority (staging); an image/audio asset is NEVER authority (it is a thing built BY a spec).
export function readySpecs() {
  const idx = readIndex();
  const rows = Array.isArray(idx.assets) ? idx.assets : [];
  return rows.filter((a) => a && a.kind === "spec" && a.state === "ready");
}

// THE authority hash — the SINGLE definition (15.24):
// sha1(join(sorted(readySpecs.map(s => id:rev:contentHash)))). `rev` is the monotonic authority-generation
// (§15a — bumped by upload/REPLACE/instructions/answer/state), so add/remove/edit of a Ready spec all move the
// hash; `contentHash` folds in as belt-and-suspenders (null for an instructions-body spec). Sorted → order-
// independent + deterministic. EMPTY authority → "" (falsy → authorityChanged stays false; the authorityEmpty gate
// keys on readySpecCount, not on this being "").
export function authorityHashOf(specs = readySpecs()) {
  const comps = (specs || []).map((s) => `${s.id}:${s.rev}:${s.contentHash || ""}`).sort();
  if (!comps.length) return "";
  return sha1hex(comps.join("\n"));
}

// The authority BODY of a spec = its `instructions` (the splitter + spec-legacy store the spec text there so a
// GUI edit of the Instructions textarea IS a spec edit) OR, if empty, its committed artifact file bytes.
function specBody(m) {
  const instr = String((m && m.instructions) || "").trim();
  if (instr) return instr;
  if (m && m.file) { try { return readFileSync(`${assetsDir()}/${m.id}/${m.file}`, "utf8"); } catch {} }
  return "";
}

// Compile the Ready spec set → spec-doc.md (north-star) + spec-index.json; RETURN {hash, ids, count}. Held under
// the assets-index lock for the WHOLE scan+write (15.24). Reads FULL metas (readAsset) for each ready spec's body
// (the derived index row omits `instructions`). Deterministic: specs sorted by id, no wall-clock in spec-doc.md.
export function compileSpecs() {
  const lock = acquire(locksDir(), "assets-index");
  try {
    const rows = readySpecs().slice().sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
    const hash = authorityHashOf(rows);
    const ids = rows.map((r) => r.id);
    let doc = `<!-- Cosmo Canyon COMPILED spec authority — ${ids.length} Ready spec(s). DERIVED from control/assets (Ready specs only; Not-Ready EXCLUDED = the primary WIP wall). Do NOT hand-edit — regenerated by spec-compile.mjs. -->\n`;
    const index = { hash, count: ids.length, specs: [] };
    for (const row of rows) {
      let m = null; try { m = readAsset(row.id); } catch {}
      const key = (m && (m.manifestKey || m.filename)) || row.manifestKey || row.filename || row.id;
      const body = specBody(m).trim();
      doc += `\n\n## SPEC ${key}  <!-- ${row.id} rev${row.rev} -->\n\n${body}\n`;
      index.specs.push({ id: row.id, key, rev: row.rev, contentHash: row.contentHash || null });
    }
    if (!ids.length) doc += `\n\n<!-- EMPTY AUTHORITY: no Ready specs. Mark a Spec asset Ready to populate the north-star (§15.33). -->\n`;
    mkdirSync(controlRoot(), { recursive: true });
    atomicWrite(specDocPath(), doc);
    atomicWrite(specIndexPath(), JSON.stringify(index, null, 2) + "\n");
    return { hash, ids, count: ids.length };
  } finally { release(lock); }
}

// §15.5 — the last-GREEN authority snapshot (Ready-spec-id set + hash). Written at each green commit (post-tick +
// supervisor); the `audit` planner mode diffs drift against THIS, not the live set (a fat-finger Ready→Not-Ready
// toggle must not immediately cascade removal pressure). Deterministic (sorted ids); atomic write.
export function writeKnownGood() {
  const specs = readySpecs();
  const kg = { ids: specs.map((s) => s.id).sort(), hash: authorityHashOf(specs), at: nowIso() };
  mkdirSync(controlRoot(), { recursive: true });
  atomicWrite(knownGoodPath(), JSON.stringify(kg, null, 2) + "\n");
  return kg;
}
export function readKnownGood() { return readJsonSafe(knownGoodPath(), null); }

// ── tiny ops CLI: `node spec-compile.mjs [compile|hash|known-good]` ─────────────────────────────────
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const cmd = process.argv[2] || "compile";
  if (cmd === "compile") { const r = compileSpecs(); console.log(JSON.stringify(r)); }
  else if (cmd === "hash") { console.log(authorityHashOf()); }
  else if (cmd === "known-good") { console.log(JSON.stringify(writeKnownGood())); }
  else { console.error("usage: node spec-compile.mjs [compile|hash|known-good]"); process.exit(2); }
}
